# Generated by Django 5.1.4 on 2025-01-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.JSONField(default=dict),
        ),
    ]
