# Generated by Django 5.1.4 on 2025-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="readable_content",
            field=models.TextField(default=""),
        ),
    ]
